package com.tdd.galaxy;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.ArrayList;
import java.util.List;

import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'BMRINAL' at '12/15/16 2:41 PM' with Gradle 2.14.1
 *
 * @author BMRINAL, @date 12/15/16 2:41 PM
 */
public class NumberSpec {
	@Test
	public void returnRomanNumber() {
		List<Number> numbers = new ArrayList<Number>();
		numbers.add(new Number("I"));
		numbers.add(new Number("II"));
		numbers.add(new Number("III"));
		numbers.add(new Number("IV"));
		numbers.add(new Number("V"));
		numbers.add(new Number("MMVI"));
		assertThat(numbers).extractingResultOf("toArabic").contains(1,2,3,4,5,2006);

	}
}
